BlogProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('mdeditor/', include('mdeditor.urls')),
    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
    path('users/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path, re_path
from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.login, name="login"),
    path('register/', views.register, name="register"),
]

blog/urls.py
from django.urls import path, re_path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('category/<int:category_id>/', views.category_list, name="category"),
    path('detail/<int:article_id>/', views.detail_blog, name="detail"),
    path('dates/<int:year>/<int:month>/', views.blog_with_dates, name="dates"),
    path('read_nums/', views.read_num_s, name="read_nums")  # 统计计数页面
]

comment/urls.py
from django.urls import path, re_path
from . import views


app_name = 'comment'
urlpatterns = [
    path('update_comment/', views.update_comment, name="update_comment"),
]

blog/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from mdeditor.fields import MDTextField
# Create your models here.
from read_record.models import ReadNum, ReadDetail, ReadNumExpandMethod


class Category(models.Model):
    """博客分类"""
    name = models.CharField('分类名称', max_length=32)
    slug = models.SlugField('slug', max_length=64)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")
    desc = models.TextField('分类描述', max_length=200)
    add_date = models.DateTimeField(auto_now_add=True)
    pub_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = "博客分类"

    def __str__(self):
        return self.name


class Tag(models.Model):
    """文章标签"""
    name = models.CharField('标签', max_length=20)
    add_date = models.DateTimeField(auto_now_add=True)
    pub_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = "标签管理"

    def __str__(self):
        return self.name


class Article(models.Model, ReadNumExpandMethod):
    """文章管理"""
    HAS_PUB_CHOICES = (
        (0, '发布'),
        (1, '存草稿'),
    )
    HAS_REPRINT_CHOICES = (
        (0, '原创'),
        (1, '转载'),
    )

    title = models.CharField('文章标题', max_length=100)
    slug = models.SlugField('slug', max_length=100, blank=True, null=True, help_text="链接后缀，必须为英文字符")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="作者")
    read_details = GenericRelation(ReadDetail)  # 关联到这个模型，可以很方便的访问关联模型的所有数据
    desc = models.TextField(max_length=100, blank=True, help_text="文章简介，字数保持在100以内！")
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE, verbose_name="专题", blank=True, null=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name="分类")
    picture = models.ImageField('封面图', upload_to='images/', max_length=200, blank=True, null=True)
    content = MDTextField()
    tags = models.ManyToManyField('Tag', blank=True)
    has_pub = models.PositiveSmallIntegerField('是否发布',choices=HAS_PUB_CHOICES, default=0)
    has_reprint = models.PositiveSmallIntegerField('是否原创', choices=HAS_REPRINT_CHOICES, default=0)
    has_url = models.URLField('原文链接', blank=True, null=True)
    add_date = models.DateTimeField(auto_now_add=True)
    pub_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = "文章管理"

    def __str__(self):
        return self.title


class Topic(models.Model):
    """专题管理"""
    name = models.CharField('专题名称', max_length=200)
    slug = models.SlugField('slug', max_length=100)
    desc = models.TextField('专题描述', max_length=300, blank=True, null=True)
    add_date = models.DateTimeField(auto_now_add=True)
    pub_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = "专题管理"

    def __str__(self):
        return self.name
        

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect, HttpResponseRedirect
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache, caches
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView, CreateView
from django.utils import timezone
from django.db.models import Sum   # 引用求和的方法
# Create your views here.
import markdown
import datetime
from .models import Article, Category, Topic
from comment.models import Comment
from comment.forms import CommentForm
from read_record.utils import read_record_once_read, get_seven_days_data,\
    get_today_hot_data, get_yesterday_hot_data  # 计数


class IndexView(ListView):
    # model = Article
    context_object_name = 'article_list'
    queryset = Article.objects.filter(has_pub=0)  # 只显示已经发布的文章
    paginate_by = 3
    template_name = 'blog/index.html'


def category_list(request, category_id):
    """栏目列表详情页"""
    category = get_object_or_404(Category, id=category_id)
    article_list = category.article_set.filter(has_pub=0)
    # 分页
    paginator = Paginator(article_list, per_page=2, orphans=1)
    pages = paginator.page_range  # 生成所有页码
    pages_num = paginator.num_pages  # 总页数
    # gd_page = paginator.page(2)  # 调用指定页面的内容
    page = request.GET.get('page')  # 当前页面
    # 当前页并具有处理超出页码范围的状况，页码不是数字返回第一页，超出返回最后一页
    contacts = paginator.get_page(page)
    return render(request, 'blog/category_list.html', locals())


def detail_blog(request, article_id):
    """文章详情页"""
    article = get_object_or_404(Article, id=article_id)

    # markdown编辑器前端显示
    article.content = markdown.markdown(article.content.replace("\r\n", '  \n'), extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',  # 语法高亮
        'markdown.extensions.toc',   # 自动生成目录
    ], safe_mode=True, enable_attributes=False)

    per_blog = Article.objects.filter(pub_date__gt=article.pub_date, has_pub=0).last()   # 上一篇
    next_blog = Article.objects.filter(pub_date__lt=article.pub_date, has_pub=0).first()  # 下一篇
    # 获取到评论列表数据
    article_content_type = ContentType.objects.get_for_model(article)
    comments = Comment.objects.filter(content_type=article_content_type, object_id=article_id)

    # 获取到评论框
    form = CommentForm(initial={'content_type': article_content_type.model, 'object_id': article_id})
    # 获取到阅读的cookie
    read_cookie_key = read_record_once_read(request, article)
    response = render(request, 'blog/detail.html', locals())
    response.set_cookie(read_cookie_key, 'true')  # 阅读cookie标记
    return response


def blog_with_dates(request, year, month):
    """文章归档列表页"""
    blog_dates = Article.objects.filter(pub_date__year=year, pub_date__month=month, has_pub=0)  # 以月份归档
    # 分页
    paginator = Paginator(blog_dates, per_page=2, orphans=1)
    pages = paginator.page_range  # 生成所有页码
    pages_num = paginator.num_pages  # 总页数
    gd_page = paginator.page(2)  # 调用指定页面的内容
    page = request.GET.get('page')  # 当前页面
    # 当前页并具有处理超出页码范围的状况，页码不是数字返回第一页，超出返回最后一页
    contacts = paginator.get_page(page)
    return render(request, 'blog/page.html', locals())


def get_seven_days_hot_articles(i):
    """七日阅读统计方法"""
    today = timezone.now().date()
    date = today - datetime.timedelta(days=i)
    article_list = Article.objects.filter(read_details__date__lt=today, read_details__date__gte=date)\
        .values('id', 'title').annotate(read_nums_sum=Sum('read_details__read_nums'))\
        .order_by('-read_nums_sum')
    return article_list[:7]


def read_num_s(request):
    """统计计数显示页面"""
    article_content_type = ContentType.objects.get_for_model(Article)  # 获取文章模型
    dates, read_num_s = get_seven_days_data(article_content_type)

    # 获取七日热门博客的缓存数据
    hot_article_for_seven_days = cache.get('hot_article_for_seven_days')
    if hot_article_for_seven_days is None:
        hot_article_for_seven_days = get_seven_days_hot_articles(7)
        cache.set('hot_article_for_seven_days', hot_article_for_seven_days, 3600)
        print('计算缓存')
    else:
        print('使用缓存')


    # 当日热门文章统计显示
    today_hot_data = get_today_hot_data(article_content_type)
    # 昨日热门文章统计显示
    yesterday_hot_data = get_yesterday_hot_data(article_content_type)
    # 七日热门阅读统计显示
    # hot_article_for_seven_days = hot_article_for_seven_days
    # 一个月内热门阅读统计显示
    hot_article_for_month_days = get_seven_days_hot_articles(30)
    return render(request, 'blog/read_nums.html', locals())

templates/blog/category_list.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block head %}
    <title>{{ category.name }}--博客分类</title>
    <meta name="Copyright" content="幸福关中通过Django开发的博客系统" />
    <meta name="keywords" content="Python, Django, framework, open-source" />
    <meta name="description" content="{{ category.desc }}" />
{% endblock %}

{% block section %}
      <div class="box has-background-white is-radiusless is-shadowless">
          <div class="content">
              <p class="is-pulled-left">
                  <span class="has-text-weight-bold is-size-4">{{ category }}&nbsp;<span class="tag is-info">{% get_articel_nums category.id %}篇</span></span> <br>
                  <span class="is-size-6">分类目录</span>
              </p>
              <a href="" class="button is-warning is-pulled-right">
                  <span class="icon">
                      <i class="fas fa-rss"></i>
                  </span>
                  <span>RSS</span>
              </a>
              <div class=" is-clearfix"></div>
              <p class=" has-text-justified is-size-7">
                  {{ category.desc }}
              </p>
          </div>
      </div>

  {% if contacts %}
  {% for article in contacts %}
  <div class="card is-shadowless" style="margin-bottom: 30px;">
    {% if article.picture %}
      <div class="card-image">
          <figure class="image is-3by1">
              <img src="{{ MEDIA_URL }}{{ article.picture }}" alt="{{ article.title }}">
          </figure>
      </div>
    {% endif %}
      <header class="card-header is-shadowless">
          <a href="{% url 'blog:detail' article.id %}" class="card-header-title card-title">
              {{ article.title }}
          </a><span class="tag is-info is-radiusless">{{ article.get_has_reprint_display }}</span>
      </header>
      <div class="card-content">
          <div class="content">
              <p class="has-text-justified" style="padding-left: 20px">
                  {{ article.content|truncatechars:100 }}
              </p>
              <a href="{% url 'blog:detail' article.id %}" class=" button is-radiusless is-medium is-link is-outlined" >
                  <span class="is-size-6">阅读更多</span>
                  <span class="icon is-size-6">
                      <i class="fas fa-arrow-right"></i>
                  </span>
              </a>
          </div>
      </div>
      <footer class="card-footer has-background-light">
          <ul class="is-inline-block">
              <li class="is-inline-block">
                  <span class="icon is-small">
                      <i class="fa fa-calendar-alt"></i>
                  </span>
                  <span>{{ article.add_date }} </span>
              </li>
              <li class="is-inline-block">
                  <span class="icon is-small">
                      <i class="fa fa-user"></i>
                  </span>
                  <span><a href="">{{ article.author }}</a></span>
              </li>
              <li class="is-inline-block">
                  <span class="icon is-small">
                      <i class="fa fa-folder-open"></i>
                  </span>
                  <span><a href="{% url 'blog:category' article.category.id %}">{{ article.category.name }}</a></span>
              </li>
              <li class="is-inline-block">
                  <span class="icon is-small">
                      <i class="fa fa-comments"></i>
                  </span>
                  <span><a href="">发表评论</a></span>
              </li>
              {% if user.is_authenticated %}
              <li class="is-inline-block">
                  <span class="icon is-small">
                      <i class="fa fa-pencil-alt"></i>
                  </span>
                  <span><a href="">编辑</a></span>
              </li>
              {% endif %}
          </ul>
      </footer>
  </div>
    {% endfor %}
    {% else %}
      <p class="has-text-centered has-text-info" style="line-height: 80px">此栏目下还没有发表任何文章！</p>
    {% endif %}

<nav class="pagination is-centered" role="navigation" aria-label="pagination">
{% if contacts.has_previous %}
  <a class="pagination-previous is-radiusless has-background-white" href="?page={{ contacts.previous_page_number }}">Previous</a>
{% endif %}
{% if contacts.has_next %}
  <a class="pagination-next is-radiusless has-background-white" href="?page={{ contacts.next_page_number }}">Next page</a>
{% endif %}
  <ul class="pagination-list">
  <li><a class="pagination-link is-radiusless has-background-white" aria-label="Goto page 1" href="?page={{ contacts.start_index }}">第一页</a></li>
      {% for page in pages %}
    {% if page == contacts.number %}
        <li><a class="pagination-link is-current is-radiusless" href="?page={{ page }}">{{ page }}</a></li>
    {% else %}
        <li><a class="pagination-link is-radiusless has-background-white" href="?page={{ page }}">{{ page }}</a></li>
    {% endif %}
{% endfor %}

    <li><a class="pagination-link is-radiusless has-background-white" aria-label="Goto page 86" href="?page={{ contacts.end_index }}">最后一页</a></li>
  </ul>
</nav>

{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
  <title>{{ article.title }} -幸福关中的博客 </title>
  <link rel="stylesheet" type="text/css" href="{% static 'blog/css/code.css' %}">
{#  <script src="https://cdn.ckeditor.com/ckeditor5/12.1.0/classic/ckeditor.js"></script>#}

{% endblock head %}

{% block section %}
<div class="card is-shadowless" style="margin-bottom: 30px;">

    <header class="card-header is-shadowless">
        <a class="card-header-title card-title">
            {{ article.title }}
        </a>
    </header>

    {% if article.picture %}
    <div class="card-image">
        <figure class="image is-3by1">
            <img src="{{ MEDIA_URL }}{{ article.picture }}" alt="{{ article.title }}">
        </figure>
    </div>
    {% endif %}
    <footer class="card-footer has-background-light">
        <ul class="is-inline-block">
            <li class="is-inline-block">
                <span class="icon is-small">
                    <i class="fa fa-calendar-alt"></i>
                </span>
                <span>{{ article.pub_date }} </span>
            </li>
            <li class="is-inline-block">
                <span class="icon is-small">
                    <i class="fa fa-folder-open"></i>
                </span>
                <span><a href="{% url 'blog:category' article.category.id %}">{{ article.category.name }}</a></span>
            </li>
            <li class="is-inline-block">
                <span class="icon is-small">
                    <i class="fa fa-book-reader"></i>
                </span>
                <span>阅读({{ article.get_read_num }})</span>
            </li>
            {% if user.is_authenticated %}
            <li class="is-inline-block">
                <span class="icon is-small">
                    <i class="fa fa-pencil-alt"></i>
                </span>
                <span><a href="">编辑</a></span>
            </li>
            {% endif %}
        </ul>
    </footer>
    <div class="card-content">
        <div class="content has-text-justified" style="padding: 0 15px;">

        {{ article.content | safe}}

        </div>
    </div>
    <div class="page">
        <nav class="pagination is-centered" role="navigation" aria-label="pagination">
        {% if per_blog %}
            <div class="pagination-previous is-radiusless is-block has-text-left" style="border: none">
                <p class="is-size-7">前一页</p>
                <a href="{% url 'blog:detail' per_blog.id %}" class="">{{ per_blog}}</a>
            </div>
            {% else %}
            <div class="pagination-previous is-radiusless is-block has-text-left" style="border: none">
                <p class="is-size-7">前一页</p>
{#                <a href="{% url 'blog:detail' per_blog.id %}" class="">{{ per_blog}}</a>#}
            <p class="has-text-danger">前一页什么也没有了，所以不要点了</p>
            </div>
        {% endif %}
            {% if next_blog %}
            <div class="pagination-next is-radiusless is-block has-text-right" style="border: none">
                <p class="is-size-7"> 后一页</p>
                <a href="{% url 'blog:detail' next_blog.id %}" class="">{{ next_blog }}</a>
            </div>
                {% else %}
            <div class="pagination-previous is-radiusless is-block has-text-left" style="border: none">
                <p class="is-size-7">后一页</p>
            <p class="has-text-danger">后一页什么也没有了，所以不要点了</p>
            </div>
            {% endif %}
        </nav>
    </div>

     <div class="page has-background-light">
         <article class="media">
             <figure class="media-left">
                 <p class="image is-64x64">
                     <img src="https://bulma.io/images/placeholders/128x128.png">

                 </p>
             </figure>
             <div class="media-content">
                 <div class="content">
                     <h2>{{ article.author.username }}</h2>
                     <p>
                         这是个人说明信息，看看是否显示！这是个人说明信息，看看是否显示！这是个人说明信息，
                         看看是否显示！这是个人说明信息，
                         看看是否显示！这是个人说明信息，看看是否显示！这是个人说明信息，看看是否显示！
                     </p>
                 </div>
                 <p class="buttons">
                     <a href="" class="button is-info" style="padding: 0 20px">
                         <span class="icon">
                             <i class="fa fa-thumbtack"></i>
                         </span>
                         <span>{{ article.author.article_set.count }}</span>
                     </a>
                     <a href="" class="button is-link">
                         <i class="fab fa-qq"></i>
                     </a>
                     <a href="" class="button is-success">
                         <i class="fab fa-weixin"></i>
                     </a>
                     <a href="" class="button is-danger">
                         <i class="fab fa-weibo"></i>
                     </a>
                     <a href="" class="button is-black">
                         <i class="fab fa-github"></i>
                     </a>
                     <a href="" class="button is-warning">
                         <i class="fas fa-rss"></i>
                     </a>
                 </p>
             </div>
         </article>
     </div>


    <!--登录后 评论 -->

    <div class="card-content">
            <div class="content">
                {% if user.is_authenticated %}
                <h2 class="has-text-weight-bold1" style="padding:0 20px 0 15px">{{ request.user }}欢迎您对 “{{ article.title }}；</h2>
                <!-- <small>电子邮件地址不会被公开。必填项已用*标注</small> -->
                    {% else %}
                    <h2 class="has-text-weight-bold" style="padding:0 20px 0 15px">评论列表</h2>
                {% endif %}
            </div>
      <div class="page">
        {% for comment in comments %}
        <article class="media">
            <figure class="media-left">
                <p class="image is-48x48">
                    <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                </p>
            </figure>
            <div class="media-content">
                <div class="content is-normal">
                <p style="white-space:normal;">
                    <strong>{{ comment.author }}</strong> <br>
                    <small class="is-size-7">{{ comment.comment_time }}</small><br>
{#                 &nbsp;<span class="is-size-7">/</span>&nbsp;    <a class=" is-size-7" href="">编辑</a> <br>#}
                    {{ comment.comment_text }}
                </p>
                </div>

        {% for reply in comment.parent_comment.all  %}
         <article class="media">
            <figure class="media-left">
                <p class="image is-48x48">
                    <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                </p>
            </figure>
            <div class="media-content">
                <div class="content is-normal">
                <p style="white-space:normal;">
                    <strong>{{ reply.author.username }}</strong> <br>
                    <small class="is-size-7">{{ reply.comment_time }}</small> &nbsp;<span class="is-size-7">/</span>&nbsp; <a class=" is-size-7" href="">编辑</a> <br>
                    {{ reply.comment_text }}
                </p>
                </div>


            </div>
{#            <div class="media-right">#}
{#                <a href="" class="button is-radiusless is-shadowless is-normal"> <span class="is-size-7">回复</span> </a>#}
{#            </div>#}

        </article>
        {% endfor %}
            </div>
{#            <div class="media-right">#}
{#                <button class="button is-info is-radiusless is-shadowless is-normal"> <span class="is-size-7">回复</span> </button>#}
{#            </div>#}

        </article>
            {% empty %}
            暂无评论
        {% endfor %}

    </div>
{% if user.is_authenticated %}
    <div class="page comment">
        <div class="content">
            <h2>发表评论</h2>

                <a class="is-size-7" href="">已登入为<span>{{ request.user }}</span>。</a> <a class="is-size-7" href="{% url 'logout' %}">登出？</a>

                <form action="{% url 'comment:update_comment' %}" method="POST" style="margin-top: 20px">
                    {% csrf_token %}
                <div class="field" id="comment">
                    <label for="" class="label">{{ request.user }}, 欢迎评论</label>
                    <div class="control">
                        {{ form }}
{#                        {{ form.media }}#}
                    </div>

                </div>
                <div class="field">
                        <div class="control">
                            <input type="submit" class="button is-info is-radiusless" value="发表评论" style="padding: 0 20px">
                        </div>
                </div>
            </form>

        </div>
    </div>

{% else %}
                <!-- comments -->

                    <!-- end comments -->
    <p>
        还没有登录，请
        <a class="button is-success is-small" href="{% url 'account:login' %}?from={{ request.get_full_path }}">登录</a>
        <span>or</span>
        <a class="button is-info is-small" href="{% url 'account:register' %}?from={{ request.get_full_path }}">注册</a>
        后发表评论！
    </p>
 {% endif %}
    </div>

    <!-- end 评论 -->

     </div>


{% endblock %}

templates/blog/detail2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/blog/footer.html
 <!-- footer -->
 <footer class="footer">
        <div class=" container has-text-centered">
             © 2019 <a href="">PythonBJ主题测试</a>.  由 <a href="">Django </a> 强力驱动. 
        </div>
    </footer>
    <!---end footer-->

templates/blog/header.html
    <!-- header -->
    <header>
            <nav class="navbar" role="navigation" aria-label="main navigation" style="height:60px;">
            <div class="container">
                <div class="navbar-brand" style="height:60px;">
                    <a href="{% url 'blog:index' %}" class="navbar-item">
                        <span class="has-text-weight-bold is-size-4 is-uppercase has-text-link">pythonBJ</span>
                    </a>
                    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample" style="height:60px">
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                    </a>
                </div>
    
                <div id="navbarBasicExample" class="navbar-menu" style="height:60px;">
                    <div class="navbar-start">
                        <div class="navbar-item">
                            <div class="field">
                                <div class="control has-icons-left has-icons-right">
                                    <input class="input is-radiusless has-background-light" type="text" placeholder="Text input">
                                      <span class="icon is-small is-left">
                                        <i class="fas fa-search"></i>
                                      </span>
                                      <!-- <span class="icon is-small is-right">
                                        <i class="fas fa-check"></i>
                                      </span> -->
                                </div>
                <!-- <p class="help is-success">This username is available</p> -->
                            </div>
                        </div>
                    </div>
                    <div class="navbar-end a-size">

                        <a href="" class="navbar-item ">首页</a>
                        <a href="" class="navbar-item">感悟</a>
                        <a href="" class="navbar-item">随笔</a>
                        <!-- <a href="" class="navbar-item">教程</a> -->
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a href="" class="navbar-link">教程</a>
                           <div class="navbar-dropdown a-size">
                               <a href="" class="navbar-item">python教程</a>
                               <a href="" class="navbar-item">Django教程</a>
                               <a href="" class="navbar-item">Vue教程</a>
                               <a href="" class="navbar-item">Typescript教程</a>
                           </div>
                        </div>
                    </div>
    
                </div>
            </div>
            </nav>
        </header>
        <!-- end header -->

templates/blog/index.html
{% extends 'base.html' %}

{% block head %}
  <title>首页 幸福关中的博客 </title>
{% endblock head %}

{% block section %}
    {% for article in article_list %}
  <div class="card is-shadowless" style="margin-bottom: 30px;">
    {% if article.picture %}
      <div class="card-image">
          <figure class="image is-3by1">
              <img src="{{ MEDIA_URL }}{{ article.picture }}" alt="{{ article.title }}">
          </figure>
      </div>
    {% endif %}
      <header class="card-header is-shadowless">
          <a href="{% url 'blog:detail' article.id %}" class="card-header-title card-title">
              {{ article.title }}
          </a><span class="tag is-info is-radiusless">{{ article.get_has_reprint_display }}</span>
      </header>
      <div class="card-content">
          <div class="content">
              <p class="has-text-justified" style="padding-left: 20px">
                  {{ article.desc }}
              </p>
              <a href="{% url 'blog:detail' article.id %}" class=" button is-radiusless is-medium is-link is-outlined" >
                  <span class="is-size-6">阅读更多</span>
                  <span class="icon is-size-6">
                      <i class="fas fa-arrow-right"></i>
                  </span>
              </a>
          </div>
      </div>
      <footer class="card-footer has-background-light">
          <ul class="is-inline-block">
              <li class="is-inline-block">
                  <span class="icon is-small">
                      <i class="fa fa-calendar-alt"></i>
                  </span>
                  <span>{{ article.add_date }} </span>
              </li>
              <li class="is-inline-block">
                  <span class="icon is-small">
                      <i class="fa fa-user"></i>
                  </span>
                  <span><a href="">{{ article.author }}</a></span>
              </li>
              <li class="is-inline-block">
                  <span class="icon is-small">
                      <i class="fa fa-folder-open"></i>
                  </span>
                  <span><a href="{% url 'blog:category' article.category.id %}">{{ article.category.name }}</a></span>
              </li>
              <li class="is-inline-block">
                  <span class="icon is-small">
                      <i class="fa fa-comments"></i>
                  </span>
                  <span><a href="">发表评论</a></span>
              </li>
              <li class="is-inline-block">
                  <span class="icon is-small">
                      <i class="fa fa-book-reader"></i>
                  </span>
                  <span>阅读({{ article.get_read_num }})</span>
              </li>
              {% if user.is_authenticated %}
              <li class="is-inline-block">
                  <span class="icon is-small">
                      <i class="fa fa-pencil-alt"></i>
                  </span>
                  <span><a href="">编辑</a></span>
              </li>
              {% endif %}
          </ul>
      </footer>
  </div>
    {% endfor %}

    <div style="padding-top: 30px">
        <nav class="pagination is-centered is-medium" role="navigation" aria-label="pagination">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" class="pagination-previous is-radiusless has-background-white">Previous</a>
             {% endif %}
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.paginator.num_pages }}" class="pagination-next is-radiusless has-background-white">Next page</a>
            {% endif %}

            <ul class="pagination-list">
                {% for page_num in page_obj.paginator.page_range %}
                    {% if page_obj.paginator.num_pages %}
                <li><a href="?page={{ page_num }}" class="pagination-link is-radiusless has-background-white" aria-label="Goto page 1">
                    {{ page_num }}</a></li>
                    {% endif %}
{#                <li><span class="pagination-ellipsis">&hellip;</span></li>#}
{#                <li><a class="pagination-link has-background-white is-radiusless" aria-label="Goto page 45">45</a></li>#}
{#                <li><a class="pagination-link is-current is-radiusless" aria-label="Page 46" aria-current="page">46</a></li>#}
{#                <li><a class="pagination-link has-background-white is-radiusless" aria-label="Goto page 47">47</a></li>#}
{#                <li><span class="pagination-ellipsis">&hellip;</span></li>#}
{#                <li><a class="pagination-link has-background-white is-radiusless" aria-label="Goto page 86">86</a></li>#}
                {% endfor %}
            </ul>
        </nav>
    </div>


{% endblock section %}